version: '3.8'

services:
  server:
    image: busybox
    command: sh -c "echo 'Message sent...' && nc -l -p 1234 -e echo 'Hello from Server!'"
    networks:
      - test-network

  client:
    image: busybox
    command: sh -c "sleep 2 && echo 'Message received...' && nc server 1234"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
