version: '3.8'
services:
  php:
    profiles:
      - disabled
    container_name: php
    image: php:apache
    command:
      - /bin/sh
      - '-c'
      - >-
        docker-php-ext-install mysqli && docker-php-ext-enable mysqli &&
        apache2-foreground
    ports:
      - '8081:80'
    volumes:
      - ./www:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
  node:
    container_name: node
    build:
      context: ./07
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - API_URL=https://localhost:3000
      extra_hosts:
        - myhost:192.168.1.1
      network: ''
      target: ''
      cache_from: []
      cache_to: []
      secrets: []
      ssh: []
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      db:
        condition: service_started
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
networks:
  app-network:
    driver: bridge
    name: app-network
