services:
  skilltree:
    container_name: skilltree
    build: ./compose
    restart: always
    # ports:
    #   - "8000:80"
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.skilltree.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.skilltree.entrypoints=websecure"
      - "traefik.http.routers.skilltree.tls.certresolver=myresolver"
#     networks:
#       web:
#       mariadb:
# networks:
#   web:
#     name: web
#     external: true
#   mariadb:
#     name: mariadb
#     external: true
