services:
  skilltree:
    container_name: skilltree
    build: ./compose
    restart: always
    ports:
      - "8080:80"
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"

