services:
  thevault:
    container_name: thevault
    build: ./compose
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.thevault.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.thevault.entrypoints=websecure"
      - "traefik.http.routers.thevault.tls.certresolver=myresolver"
#     networks:
#       web:
#       mariadb:
# networks:
#   web:
#     name: web
#     external: true
#   mariadb:
#     name: mariadb
#     external: true
